version: "3.8"

networks:
  overlay:

services:
  redis:
    image: redis:7.2.3
    command: ["sh", "-c", "rm -f /data/dump.rdb && redis-server --requirepass testpassword"]  # disable persistence
    init: true
    networks:
      - overlay

  redis-sentinel:
    image: bitnami/redis-sentinel:latest
    environment:
      - REDIS_MASTER_HOST=redis
      - REDIS_MASTER_PASSWORD=testpassword
    networks:
      - overlay
