name: Build Python util package

on:
  push:

permissions:
  contents: read # This is required for actions/checkout
  packages: write # This is required to push images to Github packages

jobs:
  package_build:
    uses: moya-app/shared-workflows/.github/workflows/python-utils.yml@tc/add-python-utils-wf
    secrets: inherit
#
